export const FISH_TYPES = [
  "Super Red Halfmoon",
  "Blue Halfmoon",
  "Royal Blue Halfmoon",
  "Mustard Gas Halfmoon",
  "Black Orchid Halfmoon",
  "Butterfly Halfmoon",
  "Marble Halfmoon",
  "Dragon Scale Halfmoon",
  "Koi Halfmoon",
  "Galaxy Koi Halfmoon",
  "Nemo Koi Halfmoon",
  "Candy Koi Halfmoon",
  "Dumbo Halfmoon",
  "Copper Halfmoon",
  "Lavender Halfmoon",
  "White Halfmoon",
  "Platinum Halfmoon",
  "Samurai Halfmoon",
  "Avatar Halfmoon",
  "Rosetail Halfmoon",
  "Feathertail Halfmoon",
  "Black Dragon Halfmoon",
  "Red Dragon Halfmoon",
  "Gold Dragon Halfmoon",
  "Full Mask Halfmoon",
  "Grizzle Halfmoon",
  "Super Red HMPK",
  "Koi HMPK",
  "Galaxy Koi HMPK",
  "Nemo HMPK",
  "Candy HMPK",
  "Samurai HMPK",
  "Black Samurai HMPK",
  "Red Samurai HMPK",
  "Avatar HMPK",
  "Dragon Scale HMPK",
  "Copper HMPK",
  "Dumbo HMPK",
  "Marble HMPK",
  "Fancy HMPK",
  "Panda HMPK",
  "Hellboy HMPK",
  "Vampire HMPK",
  "Yellow Dragon HMPK",
  "Blue Rim HMPK",
  "White Opaque HMPK",
  "Red Crowntail",
  "Blue Crowntail",
  "Butterfly Crowntail",
  "Dragon Crowntail",
  "Koi Crowntail",
  "Samurai Crowntail",
  "Copper Crowntail",
  "Marble Crowntail",
  "Dumbo Crowntail",
  "Black Crowntail",
  "Mustard Gas Crowntail",
  "Full Mask Crowntail",
  "Double Ray Crowntail",
  "Combtail",
  "Half Sun",
  "Dumbo Plakat",
  "Dumbo Koi",
  "Dumbo Galaxy Koi",
  "Dumbo Nemo",
  "Dumbo Samurai",
  "Dumbo Dragon",
  "Dumbo Avatar",
  "Dumbo Marble",
  "Dumbo Butterfly",
  "Dumbo Copper",
  "Red Dragon",
  "Black Dragon",
  "Blue Dragon",
  "Gold Dragon",
  "White Dragon",
  "Yellow Dragon",
  "Copper Dragon",
  "Dragon Koi",
  "Dragon Samurai",
  "Dragon Galaxy",
  "Dragon Plakat",
  "Koi Betta",
  "Fancy Koi",
  "Nemo Koi",
  "Galaxy Koi",
  "Candy Koi",
  "Avatar Koi",
  "Hellboy Koi",
  "Tiger Koi",
  "Marble Koi",
  "Samurai Koi",
  "Koi Plakat",
  "Samurai",
  "Black Samurai",
  "White Samurai",
  "Red Samurai",
  "Shadow Samurai",
  "Avatar",
  "Hellboy",
  "Blue Rim",
  "Armageddon",
  "Vampire",
  "Panda",
  "Tiger",
  "Nemo Candy",
  "Fancy Nemo",
  "Alien Hybrid",
  "Candy Galaxy",
  "Metallic Galaxy",
  "Yellow Fancy",
  "Iron Man Betta",
  "Copper Blood",
  "Black Orchid",
  "Purple Mosaic",
  "Golden Avatar",
];

export const WATCH_BRANDS: Record<string, string[]> = {
  Rolex: [
    "Submariner",
    "Daytona",
    "GMT-Master II",
    "Datejust",
    "Day-Date",
    "Oyster Perpetual",
    "Sky-Dweller",
    "Yacht-Master",
    "Sea-Dweller",
    "Deepsea",
    "Explorer",
    "Explorer II",
    "Air-King",
    "Milgauss",
    "Cellini",
    "Perpetual 1908",
  ],
  Seiko: [
    "Prospex",
    "Presage",
    "King Seiko",
    "Grand Seiko",
    "Astron",
    "Seiko 5 Sports",
    "Alpinist",
    "Cocktail Time",
    "Tuna",
    "Samurai",
    "Turtle",
    "Monster",
    "Willard",
    "MarineMaster",
    "Speedtimer",
  ],
  "Audemars Piguet": [
    "Royal Oak",
    "Royal Oak Offshore",
    "Royal Oak Concept",
    "Code 11.59",
    "Jules Audemars",
    "Millenary",
  ],
  Tudor: [
    "Black Bay",
    "Black Bay 58",
    "Black Bay GMT",
    "Pelagos",
    "Ranger",
    "Royal",
    "Clair de Rose",
    "1926",
    "Glamour",
    "North Flag",
    "Heritage Chrono",
  ],
  Omega: [
    "Speedmaster",
    "Seamaster",
    "Aqua Terra",
    "Planet Ocean",
    "Railmaster",
    "Constellation",
    "De Ville",
    "Globemaster",
    "Dynamic",
    "Genève",
  ],
  Fossil: [
    "Grant",
    "Townsman",
    "Machine",
    "Nate",
    "Neutra",
    "Everett",
    "Dean",
    "Copeland",
    "Carraway",
    "Fenmore",
    "Heritage",
    "Defender",
  ],
  Cartier: [
    "Santos",
    "Tank",
    "Ballon Bleu",
    "Panthère",
    "Pasha",
    "Drive de Cartier",
    "Ronde Must",
    "Baignoire",
    "Tortue",
    "Clé de Cartier",
  ],
  Casio: [
    "Edifice",
    "Oceanus",
    "Enticer",
    "MTP Series",
    "Lineage",
    "Pro Trek Analog",
    "G-Shock Analog",
    "Baby-G Analog",
    "Sheen",
  ],
};

export const PAYMENT_METHODS = ["Cash", "GCash", "Bank Transfer", "Maya", "Other"];
