/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesTimepiecesRouteImport } from './routes/sales/timepieces'
import { Route as SalesAquaticRouteImport } from './routes/sales/aquatic'
import { Route as ExpensesTimepiecesRouteImport } from './routes/expenses/timepieces'
import { Route as ExpensesAquaticRouteImport } from './routes/expenses/aquatic'
import { Route as BusinessesTimepiecesRouteImport } from './routes/businesses/timepieces'
import { Route as BusinessesLendingRouteImport } from './routes/businesses/lending'
import { Route as BusinessesAquaticRouteImport } from './routes/businesses/aquatic'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTimepiecesRoute = SalesTimepiecesRouteImport.update({
  id: '/sales/timepieces',
  path: '/sales/timepieces',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAquaticRoute = SalesAquaticRouteImport.update({
  id: '/sales/aquatic',
  path: '/sales/aquatic',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesTimepiecesRoute = ExpensesTimepiecesRouteImport.update({
  id: '/expenses/timepieces',
  path: '/expenses/timepieces',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesAquaticRoute = ExpensesAquaticRouteImport.update({
  id: '/expenses/aquatic',
  path: '/expenses/aquatic',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesTimepiecesRoute = BusinessesTimepiecesRouteImport.update({
  id: '/businesses/timepieces',
  path: '/businesses/timepieces',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesLendingRoute = BusinessesLendingRouteImport.update({
  id: '/businesses/lending',
  path: '/businesses/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesAquaticRoute = BusinessesAquaticRouteImport.update({
  id: '/businesses/aquatic',
  path: '/businesses/aquatic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/businesses/aquatic': typeof BusinessesAquaticRoute
  '/businesses/lending': typeof BusinessesLendingRoute
  '/businesses/timepieces': typeof BusinessesTimepiecesRoute
  '/expenses/aquatic': typeof ExpensesAquaticRoute
  '/expenses/timepieces': typeof ExpensesTimepiecesRoute
  '/sales/aquatic': typeof SalesAquaticRoute
  '/sales/timepieces': typeof SalesTimepiecesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/businesses/aquatic': typeof BusinessesAquaticRoute
  '/businesses/lending': typeof BusinessesLendingRoute
  '/businesses/timepieces': typeof BusinessesTimepiecesRoute
  '/expenses/aquatic': typeof ExpensesAquaticRoute
  '/expenses/timepieces': typeof ExpensesTimepiecesRoute
  '/sales/aquatic': typeof SalesAquaticRoute
  '/sales/timepieces': typeof SalesTimepiecesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/businesses/aquatic': typeof BusinessesAquaticRoute
  '/businesses/lending': typeof BusinessesLendingRoute
  '/businesses/timepieces': typeof BusinessesTimepiecesRoute
  '/expenses/aquatic': typeof ExpensesAquaticRoute
  '/expenses/timepieces': typeof ExpensesTimepiecesRoute
  '/sales/aquatic': typeof SalesAquaticRoute
  '/sales/timepieces': typeof SalesTimepiecesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/businesses/aquatic'
    | '/businesses/lending'
    | '/businesses/timepieces'
    | '/expenses/aquatic'
    | '/expenses/timepieces'
    | '/sales/aquatic'
    | '/sales/timepieces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/businesses/aquatic'
    | '/businesses/lending'
    | '/businesses/timepieces'
    | '/expenses/aquatic'
    | '/expenses/timepieces'
    | '/sales/aquatic'
    | '/sales/timepieces'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/businesses/aquatic'
    | '/businesses/lending'
    | '/businesses/timepieces'
    | '/expenses/aquatic'
    | '/expenses/timepieces'
    | '/sales/aquatic'
    | '/sales/timepieces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  BusinessesAquaticRoute: typeof BusinessesAquaticRoute
  BusinessesLendingRoute: typeof BusinessesLendingRoute
  BusinessesTimepiecesRoute: typeof BusinessesTimepiecesRoute
  ExpensesAquaticRoute: typeof ExpensesAquaticRoute
  ExpensesTimepiecesRoute: typeof ExpensesTimepiecesRoute
  SalesAquaticRoute: typeof SalesAquaticRoute
  SalesTimepiecesRoute: typeof SalesTimepiecesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/timepieces': {
      id: '/sales/timepieces'
      path: '/sales/timepieces'
      fullPath: '/sales/timepieces'
      preLoaderRoute: typeof SalesTimepiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/aquatic': {
      id: '/sales/aquatic'
      path: '/sales/aquatic'
      fullPath: '/sales/aquatic'
      preLoaderRoute: typeof SalesAquaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/timepieces': {
      id: '/expenses/timepieces'
      path: '/expenses/timepieces'
      fullPath: '/expenses/timepieces'
      preLoaderRoute: typeof ExpensesTimepiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/aquatic': {
      id: '/expenses/aquatic'
      path: '/expenses/aquatic'
      fullPath: '/expenses/aquatic'
      preLoaderRoute: typeof ExpensesAquaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/timepieces': {
      id: '/businesses/timepieces'
      path: '/businesses/timepieces'
      fullPath: '/businesses/timepieces'
      preLoaderRoute: typeof BusinessesTimepiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/lending': {
      id: '/businesses/lending'
      path: '/businesses/lending'
      fullPath: '/businesses/lending'
      preLoaderRoute: typeof BusinessesLendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/aquatic': {
      id: '/businesses/aquatic'
      path: '/businesses/aquatic'
      fullPath: '/businesses/aquatic'
      preLoaderRoute: typeof BusinessesAquaticRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  BusinessesAquaticRoute: BusinessesAquaticRoute,
  BusinessesLendingRoute: BusinessesLendingRoute,
  BusinessesTimepiecesRoute: BusinessesTimepiecesRoute,
  ExpensesAquaticRoute: ExpensesAquaticRoute,
  ExpensesTimepiecesRoute: ExpensesTimepiecesRoute,
  SalesAquaticRoute: SalesAquaticRoute,
  SalesTimepiecesRoute: SalesTimepiecesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
